import React from 'react'
import { Graph } from "react-d3-graph";
const dataFromFlask = {
  "neighbours": [
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q86XN6", 
      "entryName": "ZN761_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 761", 
      "sequence": "MAFSQGLLTFRDVAIEFSQEEWKCLDPAQRTLYRDVMLENYRNLVSLDISSKCTMKEFLSTAQGNREVFHAGTLQIHESHHNGDFCYQDVDKDIHDYEFQWQEDERNGHEAPMTKIKKLTGITERYDQSHARNKPIKDQLGSSFHSHLPEMHIFQTEEKIDNQVVKSVHDASLVSTAQRISCRPKTHISNNHGNNFWNSSLLTQKQEVHMREKSFQCNESGKAFNYSSLLRKHQIIHLADKYKCDVCGKLFNQKRNLACHRRCHTGENPYKCNECGKTFSQTSSLTCHRRLHTGEKPYKCEECDKAFHFKSILERHRIIHTEEKPYKCNECGKTFRQKSILTRHHRLHTGEKPYKCNECGKTFSHKSSLTCHHRLHTGEKPYKCNECGKTFSHKSSLTCHRRLHTGEKPYKCEECDKAYSFRSNFEIHRKIHTEDNAYKCNECGKTFSRTSSLTCHRRRHTGEQPYKCEECDKAFRFKSNLERHRRIHTGEKPYKCNECGKTFSRKSYLTCHHRLHTGEKAYKCNECGKTFSWKSSLTCHRRLHSGEKPYKCKECGKTFNQQLTLKRHRRLHSGENPYKCEDSDKAYSFKSNLEIHQKIHTEENPYKCNECGKTFSRTSSLTCHRRLHTGEKPYKCEECDKAFRVKSNLEGHRRIHTGEKPYKCNECGKTFSRKSYFICHHRLHTGEKPYKCNECGKNFSQKSSLICHHRLHTGEKPYKCNECGKTFSQKSNLTCHRRLHTGEKQV"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "A8MUZ8", 
      "entryName": "Z705G_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Putative zinc finger protein 705G", 
      "sequence": "MHSLKKLTFEDVAIDFTQEEWAMMDTSKRKLYRDVMLENISHLVSLGYQISKSYIILQLEQGKELWREGRVFLQDQNPNRESALKKTHMISMHPITRKDASTSMTMENSLILEDPFECNDSGEDCTRSSTITQCLLTHSGKKPYVSKQCGKSLRNLLSTEPHKQIHTKGKSYQCNLCEKAYTNCFHLRRHKMTHTGERPYACHLCRKAFTQCSHLRRHEKTHTGQRPYKCHQYGKVFIQSFNLQRHERTHLGKKCYECDKSGKAFSQSSGFRGNKIIHTGEKPHACLLCGKAFSLSSNLR"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "P10076", 
      "entryName": "ZFP26_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription activator activity, RNA polymerase II-specific [GO:0001228]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 26 (Zfp-26) (Protein mKR3)", 
      "sequence": "METQQVDAVTFEDVAVDFTQEEWTSLDPVQRNLYRDVMLENYQNLATVGGQMFKPSLISWLEKKVELTVIEQGILQEWEMHLKTKRTALQQDRFWSDMSNGMQLGREHSGGEPGDPVQVGAVFSEDSCPQTHSSTSNTGNTFACNLDGKDFQPLLKETSTEENIVQLNQCVKPLIFTPDVSQKKCTPEKSVECSDCGETFVNQLELQTHSSSHREKNIHKSEECGQASTHPISHGGHVIPTEKKYYECKKCEKFFTHPVYLNIHMQSHTVEKPYDCKECGKAFTERSSLIVHLRQHTREKSYECKECGKTFIQPSRLTEHMRSHTGEKPYQCDQCGNAFASSSYLTTHLRTHTGEKPFECNICGKAFTRSSYLLGHIRTHTGEKPYECKVCGKAFSGRSWLTIHLRKHTGERPYPCTECEKAFTSFAQLTEHIKTHTGEKPFRCKVCARTFRNSSCLKTHFRIHTGIKPYKCNYCGKAFTARSGLTKHVLIHNGEKPYECKECGKAFSTSSGLVEHIRIHTGEKPFECYQCGKALAHSSSLVGHLRTHTGEKPFECNQCDKTFTRSSYLRIHMRTHTGEKPYECKECGKTFPERSCLTKHIRTHTGERPYECKECGKGFISFAQLTVHIKTHSSERPFQCKVCTKSFRNSSSLETHFRIHTGVKPYKCSYCGKAFTARSGLTIHLRNHTGEKSYACQECGKAFSTSSGLIAHIRSHKGEKPFECDHCGKAFASSSYLNVHLKIHTGEKPFQCTVCGKTFTCSSYLPVHMRTHTGEKPFQCIICGKSFLWSSYLRVHMRIHTGEKPYVCQYCGKAFTEHSGLNKHLRKHTGEKPYEYKECGENFTTSADANEHETPHWGENL"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q9GZX5", 
      "entryName": "ZN350_HUMAN", 
      "geneOntology": "nuclear body [GO:0016604]; nuclear matrix [GO:0016363]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; transcription repressor complex [GO:0017053]; DNA binding [GO:0003677]; DNA-binding transcription factor activity [GO:0003700]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; RNA polymerase II intronic transcription regulatory region sequence-specific DNA binding [GO:0001162]; negative regulation of transcription by RNA polymerase II [GO:0000122]; negative regulation of transcription, DNA-templated [GO:0045892]; regulation of transcription by RNA polymerase II [GO:0006357]; regulation of transcription, DNA-templated [GO:0006355]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 350 (KRAB zinc finger protein ZFQR) (Zinc finger and BRCA1-interacting protein with a KRAB domain 1) (Zinc finger protein ZBRK1)", 
      "sequence": "MIQAQESITLEDVAVDFTWEEWQLLGAAQKDLYRDVMLENYSNLVAVGYQASKPDALFKLEQGEQLWTIEDGIHSGACSDIWKVDHVLERLQSESLVNRRKPCHEHDAFENIVHCSKSQFLLGQNHDIFDLRGKSLKSNLTLVNQSKGYEIKNSVEFTGNGDSFLHANHERLHTAIKFPASQKLISTKSQFISPKHQKTRKLEKHHVCSECGKAFIKKSWLTDHQVMHTGEKPHRCSLCEKAFSRKFMLTEHQRTHTGEKPYECPECGKAFLKKSRLNIHQKTHTGEKPYICSECGKGFIQKGNLIVHQRIHTGEKPYICNECGKGFIQKTCLIAHQRFHTGKTPFVCSECGKSCSQKSGLIKHQRIHTGEKPFECSECGKAFSTKQKLIVHQRTHTGERPYGCNECGKAFAYMSCLVKHKRIHTREKQEAAKVENPPAERHSSLHTSDVMQEKNSANGATTQVPSVAPQTSLNISGLLANRNVVLVGQPVVRCAASGDNRGFAQDRNLVNAVNVVVPSVINYVLFYVTENP"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q96NG5", 
      "entryName": "ZN558_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 558", 
      "sequence": "MAAVILPSTAAPSSLFPASQQKGHTQGGELVNELLTSWLRGLVTFEDVAVEFTQEEWALLDPAQRTLYRDVMLENCRNLASLGCRVNKPSLISQLEQDKKVVTEERGILPSTCPDLETLLKAKWLTPKKNVFRKEQSKGVKTERSHRGVKLNECNQCFKVFSTKSNLTQHKRIHTGEKPYDCSQCGKSFSSRSYLTIHKRIHNGEKPYECNHCGKAFSDPSSLRLHLRIHTGEKPYECNQCFHVFRTSCNLKSHKRIHTGENHHECNQCGKAFSTRSSLTGHNSIHTGEKPYECHDCGKTFRKSSYLTQHVRTHTGEKPYECNECGKSFSSSFSLTVHKRIHTGEKPYECSDCGKAFNNLSAVKKHLRTHTGEKPYECNHCGKSFTSNSYLSVHKRIHNRWI"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q86XN6", 
      "entryName": "ZN761_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 761", 
      "sequence": "MAFSQGLLTFRDVAIEFSQEEWKCLDPAQRTLYRDVMLENYRNLVSLDISSKCTMKEFLSTAQGNREVFHAGTLQIHESHHNGDFCYQDVDKDIHDYEFQWQEDERNGHEAPMTKIKKLTGITERYDQSHARNKPIKDQLGSSFHSHLPEMHIFQTEEKIDNQVVKSVHDASLVSTAQRISCRPKTHISNNHGNNFWNSSLLTQKQEVHMREKSFQCNESGKAFNYSSLLRKHQIIHLADKYKCDVCGKLFNQKRNLACHRRCHTGENPYKCNECGKTFSQTSSLTCHRRLHTGEKPYKCEECDKAFHFKSILERHRIIHTEEKPYKCNECGKTFRQKSILTRHHRLHTGEKPYKCNECGKTFSHKSSLTCHHRLHTGEKPYKCNECGKTFSHKSSLTCHRRLHTGEKPYKCEECDKAYSFRSNFEIHRKIHTEDNAYKCNECGKTFSRTSSLTCHRRRHTGEQPYKCEECDKAFRFKSNLERHRRIHTGEKPYKCNECGKTFSRKSYLTCHHRLHTGEKAYKCNECGKTFSWKSSLTCHRRLHSGEKPYKCKECGKTFNQQLTLKRHRRLHSGENPYKCEDSDKAYSFKSNLEIHQKIHTEENPYKCNECGKTFSRTSSLTCHRRLHTGEKPYKCEECDKAFRVKSNLEGHRRIHTGEKPYKCNECGKTFSRKSYFICHHRLHTGEKPYKCNECGKNFSQKSSLICHHRLHTGEKPYKCNECGKTFSQKSNLTCHRRLHTGEKQV"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "A8MUZ8", 
      "entryName": "Z705G_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Putative zinc finger protein 705G", 
      "sequence": "MHSLKKLTFEDVAIDFTQEEWAMMDTSKRKLYRDVMLENISHLVSLGYQISKSYIILQLEQGKELWREGRVFLQDQNPNRESALKKTHMISMHPITRKDASTSMTMENSLILEDPFECNDSGEDCTRSSTITQCLLTHSGKKPYVSKQCGKSLRNLLSTEPHKQIHTKGKSYQCNLCEKAYTNCFHLRRHKMTHTGERPYACHLCRKAFTQCSHLRRHEKTHTGQRPYKCHQYGKVFIQSFNLQRHERTHLGKKCYECDKSGKAFSQSSGFRGNKIIHTGEKPHACLLCGKAFSLSSNLR"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q9GZX5", 
      "entryName": "ZN350_HUMAN", 
      "geneOntology": "nuclear body [GO:0016604]; nuclear matrix [GO:0016363]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; transcription repressor complex [GO:0017053]; DNA binding [GO:0003677]; DNA-binding transcription factor activity [GO:0003700]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; RNA polymerase II intronic transcription regulatory region sequence-specific DNA binding [GO:0001162]; negative regulation of transcription by RNA polymerase II [GO:0000122]; negative regulation of transcription, DNA-templated [GO:0045892]; regulation of transcription by RNA polymerase II [GO:0006357]; regulation of transcription, DNA-templated [GO:0006355]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 350 (KRAB zinc finger protein ZFQR) (Zinc finger and BRCA1-interacting protein with a KRAB domain 1) (Zinc finger protein ZBRK1)", 
      "sequence": "MIQAQESITLEDVAVDFTWEEWQLLGAAQKDLYRDVMLENYSNLVAVGYQASKPDALFKLEQGEQLWTIEDGIHSGACSDIWKVDHVLERLQSESLVNRRKPCHEHDAFENIVHCSKSQFLLGQNHDIFDLRGKSLKSNLTLVNQSKGYEIKNSVEFTGNGDSFLHANHERLHTAIKFPASQKLISTKSQFISPKHQKTRKLEKHHVCSECGKAFIKKSWLTDHQVMHTGEKPHRCSLCEKAFSRKFMLTEHQRTHTGEKPYECPECGKAFLKKSRLNIHQKTHTGEKPYICSECGKGFIQKGNLIVHQRIHTGEKPYICNECGKGFIQKTCLIAHQRFHTGKTPFVCSECGKSCSQKSGLIKHQRIHTGEKPFECSECGKAFSTKQKLIVHQRTHTGERPYGCNECGKAFAYMSCLVKHKRIHTREKQEAAKVENPPAERHSSLHTSDVMQEKNSANGATTQVPSVAPQTSLNISGLLANRNVVLVGQPVVRCAASGDNRGFAQDRNLVNAVNVVVPSVINYVLFYVTENP"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "P10076", 
      "entryName": "ZFP26_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription activator activity, RNA polymerase II-specific [GO:0001228]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 26 (Zfp-26) (Protein mKR3)", 
      "sequence": "METQQVDAVTFEDVAVDFTQEEWTSLDPVQRNLYRDVMLENYQNLATVGGQMFKPSLISWLEKKVELTVIEQGILQEWEMHLKTKRTALQQDRFWSDMSNGMQLGREHSGGEPGDPVQVGAVFSEDSCPQTHSSTSNTGNTFACNLDGKDFQPLLKETSTEENIVQLNQCVKPLIFTPDVSQKKCTPEKSVECSDCGETFVNQLELQTHSSSHREKNIHKSEECGQASTHPISHGGHVIPTEKKYYECKKCEKFFTHPVYLNIHMQSHTVEKPYDCKECGKAFTERSSLIVHLRQHTREKSYECKECGKTFIQPSRLTEHMRSHTGEKPYQCDQCGNAFASSSYLTTHLRTHTGEKPFECNICGKAFTRSSYLLGHIRTHTGEKPYECKVCGKAFSGRSWLTIHLRKHTGERPYPCTECEKAFTSFAQLTEHIKTHTGEKPFRCKVCARTFRNSSCLKTHFRIHTGIKPYKCNYCGKAFTARSGLTKHVLIHNGEKPYECKECGKAFSTSSGLVEHIRIHTGEKPFECYQCGKALAHSSSLVGHLRTHTGEKPFECNQCDKTFTRSSYLRIHMRTHTGEKPYECKECGKTFPERSCLTKHIRTHTGERPYECKECGKGFISFAQLTVHIKTHSSERPFQCKVCTKSFRNSSSLETHFRIHTGVKPYKCSYCGKAFTARSGLTIHLRNHTGEKSYACQECGKAFSTSSGLIAHIRSHKGEKPFECDHCGKAFASSSYLNVHLKIHTGEKPFQCTVCGKTFTCSSYLPVHMRTHTGEKPFQCIICGKSFLWSSYLRVHMRIHTGEKPYVCQYCGKAFTEHSGLNKHLRKHTGEKPYEYKECGENFTTSADANEHETPHWGENL"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q96NG5", 
      "entryName": "ZN558_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 558", 
      "sequence": "MAAVILPSTAAPSSLFPASQQKGHTQGGELVNELLTSWLRGLVTFEDVAVEFTQEEWALLDPAQRTLYRDVMLENCRNLASLGCRVNKPSLISQLEQDKKVVTEERGILPSTCPDLETLLKAKWLTPKKNVFRKEQSKGVKTERSHRGVKLNECNQCFKVFSTKSNLTQHKRIHTGEKPYDCSQCGKSFSSRSYLTIHKRIHNGEKPYECNHCGKAFSDPSSLRLHLRIHTGEKPYECNQCFHVFRTSCNLKSHKRIHTGENHHECNQCGKAFSTRSSLTGHNSIHTGEKPYECHDCGKTFRKSSYLTQHVRTHTGEKPYECNECGKSFSSSFSLTVHKRIHTGEKPYECSDCGKAFNNLSAVKKHLRTHTGEKPYECNHCGKSFTSNSYLSVHKRIHNRWI"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q9GZX5", 
      "entryName": "ZN350_HUMAN", 
      "geneOntology": "nuclear body [GO:0016604]; nuclear matrix [GO:0016363]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; transcription repressor complex [GO:0017053]; DNA binding [GO:0003677]; DNA-binding transcription factor activity [GO:0003700]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; RNA polymerase II intronic transcription regulatory region sequence-specific DNA binding [GO:0001162]; negative regulation of transcription by RNA polymerase II [GO:0000122]; negative regulation of transcription, DNA-templated [GO:0045892]; regulation of transcription by RNA polymerase II [GO:0006357]; regulation of transcription, DNA-templated [GO:0006355]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 350 (KRAB zinc finger protein ZFQR) (Zinc finger and BRCA1-interacting protein with a KRAB domain 1) (Zinc finger protein ZBRK1)", 
      "sequence": "MIQAQESITLEDVAVDFTWEEWQLLGAAQKDLYRDVMLENYSNLVAVGYQASKPDALFKLEQGEQLWTIEDGIHSGACSDIWKVDHVLERLQSESLVNRRKPCHEHDAFENIVHCSKSQFLLGQNHDIFDLRGKSLKSNLTLVNQSKGYEIKNSVEFTGNGDSFLHANHERLHTAIKFPASQKLISTKSQFISPKHQKTRKLEKHHVCSECGKAFIKKSWLTDHQVMHTGEKPHRCSLCEKAFSRKFMLTEHQRTHTGEKPYECPECGKAFLKKSRLNIHQKTHTGEKPYICSECGKGFIQKGNLIVHQRIHTGEKPYICNECGKGFIQKTCLIAHQRFHTGKTPFVCSECGKSCSQKSGLIKHQRIHTGEKPFECSECGKAFSTKQKLIVHQRTHTGERPYGCNECGKAFAYMSCLVKHKRIHTREKQEAAKVENPPAERHSSLHTSDVMQEKNSANGATTQVPSVAPQTSLNISGLLANRNVVLVGQPVVRCAASGDNRGFAQDRNLVNAVNVVVPSVINYVLFYVTENP"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "P10076", 
      "entryName": "ZFP26_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription activator activity, RNA polymerase II-specific [GO:0001228]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 26 (Zfp-26) (Protein mKR3)", 
      "sequence": "METQQVDAVTFEDVAVDFTQEEWTSLDPVQRNLYRDVMLENYQNLATVGGQMFKPSLISWLEKKVELTVIEQGILQEWEMHLKTKRTALQQDRFWSDMSNGMQLGREHSGGEPGDPVQVGAVFSEDSCPQTHSSTSNTGNTFACNLDGKDFQPLLKETSTEENIVQLNQCVKPLIFTPDVSQKKCTPEKSVECSDCGETFVNQLELQTHSSSHREKNIHKSEECGQASTHPISHGGHVIPTEKKYYECKKCEKFFTHPVYLNIHMQSHTVEKPYDCKECGKAFTERSSLIVHLRQHTREKSYECKECGKTFIQPSRLTEHMRSHTGEKPYQCDQCGNAFASSSYLTTHLRTHTGEKPFECNICGKAFTRSSYLLGHIRTHTGEKPYECKVCGKAFSGRSWLTIHLRKHTGERPYPCTECEKAFTSFAQLTEHIKTHTGEKPFRCKVCARTFRNSSCLKTHFRIHTGIKPYKCNYCGKAFTARSGLTKHVLIHNGEKPYECKECGKAFSTSSGLVEHIRIHTGEKPFECYQCGKALAHSSSLVGHLRTHTGEKPFECNQCDKTFTRSSYLRIHMRTHTGEKPYECKECGKTFPERSCLTKHIRTHTGERPYECKECGKGFISFAQLTVHIKTHSSERPFQCKVCTKSFRNSSSLETHFRIHTGVKPYKCSYCGKAFTARSGLTIHLRNHTGEKSYACQECGKAFSTSSGLIAHIRSHKGEKPFECDHCGKAFASSSYLNVHLKIHTGEKPFQCTVCGKTFTCSSYLPVHMRTHTGEKPFQCIICGKSFLWSSYLRVHMRIHTGEKPYVCQYCGKAFTEHSGLNKHLRKHTGEKPYEYKECGENFTTSADANEHETPHWGENL"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "A8MUZ8", 
      "entryName": "Z705G_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Putative zinc finger protein 705G", 
      "sequence": "MHSLKKLTFEDVAIDFTQEEWAMMDTSKRKLYRDVMLENISHLVSLGYQISKSYIILQLEQGKELWREGRVFLQDQNPNRESALKKTHMISMHPITRKDASTSMTMENSLILEDPFECNDSGEDCTRSSTITQCLLTHSGKKPYVSKQCGKSLRNLLSTEPHKQIHTKGKSYQCNLCEKAYTNCFHLRRHKMTHTGERPYACHLCRKAFTQCSHLRRHEKTHTGQRPYKCHQYGKVFIQSFNLQRHERTHLGKKCYECDKSGKAFSQSSGFRGNKIIHTGEKPHACLLCGKAFSLSSNLR"
    }, 
    {
      "crossReferenceInterPro": "IPR003604;IPR036236;IPR013087;", 
      "entry": "B0JZ85", 
      "entryName": "ZN346_XENTR", 
      "geneOntology": "cytoplasm [GO:0005737]; nucleus [GO:0005634]; double-stranded RNA binding [GO:0003725]; zinc ion binding [GO:0008270]", 
      "jaccard": 0.7857142857142857, 
      "proteinNames": "Zinc finger protein 346 (Just another zinc finger protein) (Protein jaz)", 
      "sequence": "MADEFGDGDTVELPVGKEAVDALIRENSHIFSDTQCKVCSAVLISESQKLAHYQSRKHANKVRRYMSIHQGEEFVSAKKFKAAPAESSDGDDRSKCCPICNMTFSSPVVAESHYSGKTHIKNLRLREQGGVTEGMLHQAKKLVVTRTPTIATKIDNRMDQSDPTKFCKLCHATFNNPLMAEQHYAGKKHKKQETKTQLMTIYTSSGHTPAQAPIAINVNSPLPGSGSAGKGFSCDTCNIVLNSIEQYQAHVSGAKHKNQLMSMTPLSKEGPPAAGGPSALAGPPSTGGALSSGGPSARGFSASGGPTPKGPSSFGGLPPMGGLMPPPYPPPHSQPYVREDMMGPDGYTYFNKDF"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q86XN6", 
      "entryName": "ZN761_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 761", 
      "sequence": "MAFSQGLLTFRDVAIEFSQEEWKCLDPAQRTLYRDVMLENYRNLVSLDISSKCTMKEFLSTAQGNREVFHAGTLQIHESHHNGDFCYQDVDKDIHDYEFQWQEDERNGHEAPMTKIKKLTGITERYDQSHARNKPIKDQLGSSFHSHLPEMHIFQTEEKIDNQVVKSVHDASLVSTAQRISCRPKTHISNNHGNNFWNSSLLTQKQEVHMREKSFQCNESGKAFNYSSLLRKHQIIHLADKYKCDVCGKLFNQKRNLACHRRCHTGENPYKCNECGKTFSQTSSLTCHRRLHTGEKPYKCEECDKAFHFKSILERHRIIHTEEKPYKCNECGKTFRQKSILTRHHRLHTGEKPYKCNECGKTFSHKSSLTCHHRLHTGEKPYKCNECGKTFSHKSSLTCHRRLHTGEKPYKCEECDKAYSFRSNFEIHRKIHTEDNAYKCNECGKTFSRTSSLTCHRRRHTGEQPYKCEECDKAFRFKSNLERHRRIHTGEKPYKCNECGKTFSRKSYLTCHHRLHTGEKAYKCNECGKTFSWKSSLTCHRRLHSGEKPYKCKECGKTFNQQLTLKRHRRLHSGENPYKCEDSDKAYSFKSNLEIHQKIHTEENPYKCNECGKTFSRTSSLTCHRRLHTGEKPYKCEECDKAFRVKSNLEGHRRIHTGEKPYKCNECGKTFSRKSYFICHHRLHTGEKPYKCNECGKNFSQKSSLICHHRLHTGEKPYKCNECGKTFSQKSNLTCHRRLHTGEKQV"
    }, 
    {
      "crossReferenceInterPro": "IPR000210;IPR011333;IPR036236;IPR013087;", 
      "entry": "Q92010", 
      "entryName": "ZBT14_CHICK", 
      "geneOntology": "nucleoplasm [GO:0005654]; nucleus [GO:0005634]; DNA-binding transcription factor activity [GO:0003700]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; sequence-specific DNA binding [GO:0043565]; transcription cis-regulatory region binding [GO:0000976]; negative regulation of transcription, DNA-templated [GO:0045892]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger and BTB domain-containing protein 14 (Zinc finger protein 161 homolog) (Zfp-161) (Zinc finger protein 5) (ZF5)", 
      "sequence": "MEFFISMSETIKYNDDDHKTVFLKTLNEQRLEGEFCDIAIVVEDVKFRAHRCVLAACSTYFKKLFKKLEVDSSSVIEIDFLRSDIFEEVLNYMYTAKISVKKEDVNLMMSSGQILGIRFLDKLCSQKRDVSSPEENTQSKSKYCLKINRPIGEPNDTQDDEVEEIGDHDDSPSDVTVEGTPPSQEDGKSPTTTLRVQEAILKELGSEEVRKVNCYGQEVESMETTESKDLGSQTPQALTFNDGISEVKDEQTPGWTTAAGDMKFEYLLYGHREHIVCQACGKTFSDEARLRKHEKLHTADRPFVCEMCTKGFTTQAHLKEHLKIHTGYKPYSCEVCGKSFIRAPDLKKHERVHSNERPFACHMCDKAFKHKSHLKDHERRHRGEKPFVCGSCTKAFAKASDLKRHENNMHSERKQVTTANSIQSETEQLQAAAMAREAEQQLETIACS"
    }, 
    {
      "crossReferenceInterPro": "IPR041697;IPR036236;IPR013087;", 
      "entry": "Q8BHZ4", 
      "entryName": "ZN592_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA binding [GO:0003677]; metal ion binding [GO:0046872]", 
      "jaccard": 0.8571428571428571, 
      "proteinNames": "Zinc finger protein 592 (Zfp-592)", 
      "sequence": "MGDMKTPDFDDLLAAFDIPDPTSLDAKEAIQAPSEENESPLKSSGMCIDENVSLSHSGSAPDVPAVSVIVKNTSRQESFEAEKDHIAPSLLHNGFRGSDLPPDSHHCGKFDSTFINGDSARSFTSKLEPSKSEPLPTFNQFSPISSPEPEDPVKDNGFGIKSKHSDSYFPPPPGTVGGPVLEALSKFPVPELHMFDHFCKKEPKPEPLPLESQQEHEQGGQKVVEPHKDLDSSRFFGEALEFNSHPSNSIGEPKKLAPELSACSSVPPRQRLKPAHSKLSSCVAALVALQAKRVANVTKEDQPGHTKDSSGPTKEGSKGSPKMPKSPKSPRSPLEATRKSIKPSDSPRSICSDSSSKGSPSVAASSPPAIPKVRIKTIKTSSGEIKRTVTRILPDPDDPSKSPAESPAGSTITEAPSEAPGDEGTAMPVEEHFSEAGIHSGSPQGDRKGDENMIKTSDSSSPCRISGSRVPKGSALNSQASKKQQSTAPQASTPAASLLPKAVHLANLNLVPHSVAASVTAKSSAQRRSQPQVTQMTVPLVHQVKKAAPLIVEVFNKVLHSSNPVPLYAPNLSPPADSRIHVPASGYCCLECGDAFALEKSLSQHYSRRSVHIEVLCTLCSKTLLFFNKCSLLRHARDHKSKGLVMQCSQLLVKPISADQMFVAAPVNSTAPATPAASSSPKPSPTLDNASSVIPALPLYPDPVRLIRYGTKCPECHKQMRDYMVLATHFQRTTEETEGLTCQVCQMLLPNQCSFCAHQRIHAHKSPYCCPECGVLCRSAYFQTHVKENCLHYARKVGYRCIHCGVIHLTLALLKSHIQERHCQVFHKCAFCPMAFKTASSTMDHSTTQHPTQPHKPSQLIYKCSCEMVFNKKRHIQQHFYQNVSKTQAGVFKCPECPLLFLQKPELMQHVKNTHGVPRNVEELSSLQSSTDTSSNRPGSRAPAEPPATNVAARGSSLTAGRWGRPEAHRRAEARPRMRSTGWTCQECQEWVPDRESYVSHMKKSHGRTLKRYPCRQCEQSFHNPSSLRKHIRNNHDTVKKVYTCGYCTEDSPSFPRPSLLESHISLMHGIRNPDLSQTSKVRHPGGPSPQVNHLKRPVSRMADAPGTSNGATVSSTKRHKSLFQCAKCTFATDSELEFQSHIPQHQVDSSTAQCLLCGLCYTSTSSLNRHLFIVHKVRDQEEGGEDIVEVKVEAPDSEACSGEEVAMETKENGLEECASEPLVTDLGGQQGLALDEDSAQDPQNQPQASQDQNSHALSPQV"
    }, 
    {
      "crossReferenceInterPro": "IPR000210;IPR041588;IPR011333;IPR036236;IPR013087;", 
      "entry": "G5E8B9", 
      "entryName": "ZBT11_MOUSE", 
      "geneOntology": "nucleolus [GO:0005730]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription, DNA-templated [GO:0006355]", 
      "jaccard": 0.8571428571428571, 
      "proteinNames": "Zinc finger and BTB domain-containing protein 11", 
      "sequence": "MSSEESYRAILRYLTNEREPYAPGTEGNVKRKIRKAAACYVVRGGTLYYQRRQRHRKTFAELEVVLQPERRQGLIEAAHLGPGGTHHTRHQTWHDLSKTYWWRGILKQVKDYIKQCSKCQEKLDRSRPISDASEMLEELGLDLDSGEESNESEDDLSNFTSPPSTASKSSKKKPVSKHELVFVDTKGVVKRSSPKHCQAVLKQLNEQRLSNQFCDVTLLIEGEEYKAHKSVLSANSEYFRDLFIEKGAVSSHEAVVDLSGFCKASFLPLLEFAYTSVLSFDFCSMADVAVLARHLFMSEVLEICESVHKLMEEKQLTVYKKGEVQTVASTQDLAAHNGTTTPPGTRNEATTTLSGELGHCEIVLLVNGELPEAEQNGEPEQQPAPQASPEAEASVSPVEGIPEPHPEMGTASLAKESNQPESAVTREDGIVASVHPKISKENVTNASQEDSDTGNDTSPEDIGAKDCPDHSQSPGQPSKDEDTLTEATEKTDSGPDDDTYRSRLRQRSVNEGGYIRLHKGMEKKLQKRKAISKSAVQQVAQKLVQRGKKMKQPKRDAKESTEETAHKCGECGMVFPRRYAFIMHTLKHERARDYKCPLCKKQFQYSASLRAHLIRHTRKEAPTSSSSNSTSTEASGGSSEKGRTKREFICSICGRTLPKLYSLRIHMLKHTGVKPHACQVCGKTFIYKHGLKLHQSLHQSQKQFQCELCVKSFVTKRSLQEHMSIHTGESKYFCSICGKSFHRGSGLSKHLKKHQPKPEVRGYHCTQCEKSFFEARDLRQHMNKHLGVKPFQCQFCDKCYSWKKDWYSHVKSHSVTEPYRCNICGKEFYEKALFRRHVKKATHGKKGRAKQNLERVCDQCGRKFTQLREYRRHMNNHEGVKPFECLTCGVAWADARSLKRHVRTHTGERPYVCPVCSEAYIDARTLRKHMTKFHRDYVPCKIMLEKDTLQFHNQGTQVEHAVSILTADMQEQESSGPQELETVVVTGETMEVLEAVAATEECPSVSTLSDQSIMQVVNYVLAQQQGQKLSEVAEAIQTVEVEVAHMPEAE"
    }, 
    {
      "crossReferenceInterPro": "IPR036236;IPR013087;", 
      "entry": "B2RRE4", 
      "entryName": "Z518B_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; chromatin organization [GO:0006325]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger protein 518B", 
      "sequence": "MKDIGEQLYTTQVNGGPSSLTMSPKQPNRATRTERQEAQTLLYQGSEAEAATMTIATCVQCKSVHKIPTQDLRKGPGQSQDTYVCFKCSLRAVPTQLHFVNNNAGAAHVRNETETISSPVNKFKVRNFKPGKYYCDKCRFSTKDPLQYRKHTLQHEEIRFICSHCSYISYTKGEFQRHLVKHTGIFPYRCEYCDYGAIRNDYIVKHRRRVHERAGAKRPFKTVAKLEPKRTSIPKQSMELSKGPSPRAAFQNKLSDQLSRFSLHANKDKTHNLMLLPELKKYQKDVVCIPNKVTLSEPREVSLLGNKNVEVEVLSPSKEPVHPGMPLTVMAPSELVVPTNCLAQLMDVKVVNGAQQLVLKLFPLEENARLETSRGDGGTSECLSTEKGSGGQKKMLSPEASRSLAVEGNAGDFVGLDRLHSLVQKQLKNVKWVKSCNFFMPNSGVHSQQESFLGSDTIKELQKSHSLCPPRALPSAAIKSHSPASVQNSVPYGPGATVSHFLSKAAVAFADDRRGARSNSQQLLPLASLPSKVPFSGEKGLLPIGESDLEARNRISRPETLVSSDRKLEDKQMESKAVGNTGQVSSVQNKEYLHINITGEDKPRSQQPGDQPGQPKTSETAGATFEGPIISSVFSLSSGSENVPEAIKWNSSTTKIKSIELLRRKIAQLIESCGKPSSLSANSAQRRSIGQAPKLTSKATPKAIQEMSVSLTGPGPTPGPSVGPLQKPPNEDSITGSRQLVPQQVCPQFISANDGKMENRVTRKTPVATPVLIPKGAVLRVLNSSEDAHIIEATCDTPVSIPCSEAQLAGTLPFCPMKQTGSGSQPLTCRSGPADMSPGLETSLRPKSRKEDTICSATAKKMVPVYSTAPGSSDSIRQGRPVSRNLTVSKNKTKQVNSTKKKNKMQANPGRYFKDPPSFFQVARQLRLIAAKPDQLIKCPRRNQPVIVLNHPDVDSPEVTNVMKVINKYKGNVLKVVLSERTRCQLGVRRYHMRLTYQNVAETNHMKRQMMLKMKLKKVHKNNYQVVGSMPDDPAQCVFKCWFCGRLYEDQEEWMSHGQRHLIEATRDWDVLSSKGK"
    }, 
    {
      "crossReferenceInterPro": "IPR036236;IPR013087;", 
      "entry": "Q6ZN19", 
      "entryName": "ZN841_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription activator activity, RNA polymerase II-specific [GO:0001228]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger protein 841", 
      "sequence": "MLEGHESYDTENFYFREIRKNLQEVDFQWKDGEINYKEGPMTHKNNLTGQRVRHSQGDVENKHMENQLILRFQSGLGELQKFQTAEKIYGCNQIERTVNNCFLASPLQRIFPGVQTNISRKYGNDFLQLSLPTQDEKTHIREKPYIGNECGKAFRVSSSLINHQMIHTTEKPYRCNESGKAFHRGSLLTVHQIVHTRGKPYQCDVCGRIFRQNSDLVNHRRSHTGDKPYICNECGKSFSKSSHLAVHQRIHTGEKPYKCNRCGKCFSQSSSLATHQTVHTGDKPYKCNECGKTFKRNSSLTAHHIIHAGKKPYTCDVCGKVFYQNSQLVRHQIIHTGETPYKCNECGKVFFQRSRLAGHRRIHTGEKPYKCNECGKVFSQHSHLAVHQRVHTGEKPYKCNECGKAFNWGSLLTVHQRIHTGEKPYKCNVCGKVFNYGGYLSVHMRCHTGEKPLHCNKCGMVFTYYSCLARHQRMHTGEKPYKCNVCGKVFIDSGNLSIHRRSHTGEKPFQCNECGKVFSYYSCLARHRKIHTGEKPYKCNDCGKAYTQRSSLTKHLVIHTGENPYHCNEFGEAFIQSSKLARYHRNPTGEKPHKCSECGRTFSHKTSLVYHQRRHTGEMPYKCIECGKVFNSTTTLARHRRIHTGEKPYKCNECGKVFRYRSGLARHWSIHTGEKPYKCNECGKAFRVRSILLNHQMMHTGEKPYKCNECGKAFIERSNLVYHQRNHTGEKPYKCMECGKAFGRRSCLTKHQRIHSSEKPYKCNECGKSYISRSGLTKHQIKHAGENLTTKLNVERPLDVVLTSGIPK"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q96NG5", 
      "entryName": "ZN558_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 558", 
      "sequence": "MAAVILPSTAAPSSLFPASQQKGHTQGGELVNELLTSWLRGLVTFEDVAVEFTQEEWALLDPAQRTLYRDVMLENCRNLASLGCRVNKPSLISQLEQDKKVVTEERGILPSTCPDLETLLKAKWLTPKKNVFRKEQSKGVKTERSHRGVKLNECNQCFKVFSTKSNLTQHKRIHTGEKPYDCSQCGKSFSSRSYLTIHKRIHNGEKPYECNHCGKAFSDPSSLRLHLRIHTGEKPYECNQCFHVFRTSCNLKSHKRIHTGENHHECNQCGKAFSTRSSLTGHNSIHTGEKPYECHDCGKTFRKSSYLTQHVRTHTGEKPYECNECGKSFSSSFSLTVHKRIHTGEKPYECSDCGKAFNNLSAVKKHLRTHTGEKPYECNHCGKSFTSNSYLSVHKRIHNRWI"
    }, 
    {
      "crossReferenceInterPro": "IPR000210;IPR011333;IPR036236;IPR013087;", 
      "entry": "Q802Y8", 
      "entryName": "ZB16A_DANRE", 
      "geneOntology": "cytoplasm [GO:0005737]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; positive regulation of type I interferon production [GO:0032481]; protein ubiquitination [GO:0016567]; regulation of neurogenesis [GO:0050767]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger and BTB domain-containing protein 16-A (Promyelocytic leukemia zinc finger protein-A) (Zinc finger protein PLZF-A)", 
      "sequence": "MDLTKMGMIQLQNPNHPNALLHKANQMRLAGTLCDVVIMVDSQEFHAHRTVLACTSKMFEILFHRNSQHYTLDFLSPKTFQQILEYAYTATLQAKVEDLDDLLYAAEILEIEYLEEQCLKILETIQSSDENDTEVNMNDGGTEDDEERKGRHGRNLVGSKKHSTEESGYVSAAQQALALPGMVDQSPSVSTSFGLSTMSPTKAAVDSLMSIGQSLLQSTMHPGVGAEQPLHGNSHPMMGEIKTEMMQVDESGEHESPKAMESIASSNGERSGEPDKNRDGPGTPTRSSVITSARELHYVRDEGLGDQQAEVSQMGLEAMAGMTEKHLASLYGIPSNHKNEAMLSMPASMASSLHMSPALAMSMDFSAYGGLLPQSFIQREFFSKLGELAAGIKPDGRSLNERCNVCGAELPDNEAIEQHRKLHSGMKTYGCELCGKRFLDSLRLRMHLLSHSAGEKAIVCDQCGAQFQKEDALEAHRQIHTGSDMAIFCLLCGKRFQTQTALQQHMEVHAGVRSYICSECNRTFPSHTALKRHLRSHTAGDHPFECEFCGSCFRDESTLKGHKRIHTGEKPYECNGCGKKFSLKHQLETHYRVHTGEKPFECKLCHQRSRDYSAMIKHLRTHNGASPYQCTICLEYCPSLSAMQKHMKGHKPEDIPPDWRIEKTYLYLCYV"
    }, 
    {
      "crossReferenceInterPro": "IPR036236;IPR013087;", 
      "entry": "B2RRE4", 
      "entryName": "Z518B_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; chromatin organization [GO:0006325]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger protein 518B", 
      "sequence": "MKDIGEQLYTTQVNGGPSSLTMSPKQPNRATRTERQEAQTLLYQGSEAEAATMTIATCVQCKSVHKIPTQDLRKGPGQSQDTYVCFKCSLRAVPTQLHFVNNNAGAAHVRNETETISSPVNKFKVRNFKPGKYYCDKCRFSTKDPLQYRKHTLQHEEIRFICSHCSYISYTKGEFQRHLVKHTGIFPYRCEYCDYGAIRNDYIVKHRRRVHERAGAKRPFKTVAKLEPKRTSIPKQSMELSKGPSPRAAFQNKLSDQLSRFSLHANKDKTHNLMLLPELKKYQKDVVCIPNKVTLSEPREVSLLGNKNVEVEVLSPSKEPVHPGMPLTVMAPSELVVPTNCLAQLMDVKVVNGAQQLVLKLFPLEENARLETSRGDGGTSECLSTEKGSGGQKKMLSPEASRSLAVEGNAGDFVGLDRLHSLVQKQLKNVKWVKSCNFFMPNSGVHSQQESFLGSDTIKELQKSHSLCPPRALPSAAIKSHSPASVQNSVPYGPGATVSHFLSKAAVAFADDRRGARSNSQQLLPLASLPSKVPFSGEKGLLPIGESDLEARNRISRPETLVSSDRKLEDKQMESKAVGNTGQVSSVQNKEYLHINITGEDKPRSQQPGDQPGQPKTSETAGATFEGPIISSVFSLSSGSENVPEAIKWNSSTTKIKSIELLRRKIAQLIESCGKPSSLSANSAQRRSIGQAPKLTSKATPKAIQEMSVSLTGPGPTPGPSVGPLQKPPNEDSITGSRQLVPQQVCPQFISANDGKMENRVTRKTPVATPVLIPKGAVLRVLNSSEDAHIIEATCDTPVSIPCSEAQLAGTLPFCPMKQTGSGSQPLTCRSGPADMSPGLETSLRPKSRKEDTICSATAKKMVPVYSTAPGSSDSIRQGRPVSRNLTVSKNKTKQVNSTKKKNKMQANPGRYFKDPPSFFQVARQLRLIAAKPDQLIKCPRRNQPVIVLNHPDVDSPEVTNVMKVINKYKGNVLKVVLSERTRCQLGVRRYHMRLTYQNVAETNHMKRQMMLKMKLKKVHKNNYQVVGSMPDDPAQCVFKCWFCGRLYEDQEEWMSHGQRHLIEATRDWDVLSSKGK"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "A8MUZ8", 
      "entryName": "Z705G_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Putative zinc finger protein 705G", 
      "sequence": "MHSLKKLTFEDVAIDFTQEEWAMMDTSKRKLYRDVMLENISHLVSLGYQISKSYIILQLEQGKELWREGRVFLQDQNPNRESALKKTHMISMHPITRKDASTSMTMENSLILEDPFECNDSGEDCTRSSTITQCLLTHSGKKPYVSKQCGKSLRNLLSTEPHKQIHTKGKSYQCNLCEKAYTNCFHLRRHKMTHTGERPYACHLCRKAFTQCSHLRRHEKTHTGQRPYKCHQYGKVFIQSFNLQRHERTHLGKKCYECDKSGKAFSQSSGFRGNKIIHTGEKPHACLLCGKAFSLSSNLR"
    }, 
    {
      "crossReferenceInterPro": "IPR003604;IPR036236;IPR013087;", 
      "entry": "B0JZ85", 
      "entryName": "ZN346_XENTR", 
      "geneOntology": "cytoplasm [GO:0005737]; nucleus [GO:0005634]; double-stranded RNA binding [GO:0003725]; zinc ion binding [GO:0008270]", 
      "jaccard": 0.7857142857142857, 
      "proteinNames": "Zinc finger protein 346 (Just another zinc finger protein) (Protein jaz)", 
      "sequence": "MADEFGDGDTVELPVGKEAVDALIRENSHIFSDTQCKVCSAVLISESQKLAHYQSRKHANKVRRYMSIHQGEEFVSAKKFKAAPAESSDGDDRSKCCPICNMTFSSPVVAESHYSGKTHIKNLRLREQGGVTEGMLHQAKKLVVTRTPTIATKIDNRMDQSDPTKFCKLCHATFNNPLMAEQHYAGKKHKKQETKTQLMTIYTSSGHTPAQAPIAINVNSPLPGSGSAGKGFSCDTCNIVLNSIEQYQAHVSGAKHKNQLMSMTPLSKEGPPAAGGPSALAGPPSTGGALSSGGPSARGFSASGGPTPKGPSSFGGLPPMGGLMPPPYPPPHSQPYVREDMMGPDGYTYFNKDF"
    }, 
    {
      "crossReferenceInterPro": "IPR041697;IPR036236;IPR013087;", 
      "entry": "Q8BHZ4", 
      "entryName": "ZN592_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA binding [GO:0003677]; metal ion binding [GO:0046872]", 
      "jaccard": 0.8571428571428571, 
      "proteinNames": "Zinc finger protein 592 (Zfp-592)", 
      "sequence": "MGDMKTPDFDDLLAAFDIPDPTSLDAKEAIQAPSEENESPLKSSGMCIDENVSLSHSGSAPDVPAVSVIVKNTSRQESFEAEKDHIAPSLLHNGFRGSDLPPDSHHCGKFDSTFINGDSARSFTSKLEPSKSEPLPTFNQFSPISSPEPEDPVKDNGFGIKSKHSDSYFPPPPGTVGGPVLEALSKFPVPELHMFDHFCKKEPKPEPLPLESQQEHEQGGQKVVEPHKDLDSSRFFGEALEFNSHPSNSIGEPKKLAPELSACSSVPPRQRLKPAHSKLSSCVAALVALQAKRVANVTKEDQPGHTKDSSGPTKEGSKGSPKMPKSPKSPRSPLEATRKSIKPSDSPRSICSDSSSKGSPSVAASSPPAIPKVRIKTIKTSSGEIKRTVTRILPDPDDPSKSPAESPAGSTITEAPSEAPGDEGTAMPVEEHFSEAGIHSGSPQGDRKGDENMIKTSDSSSPCRISGSRVPKGSALNSQASKKQQSTAPQASTPAASLLPKAVHLANLNLVPHSVAASVTAKSSAQRRSQPQVTQMTVPLVHQVKKAAPLIVEVFNKVLHSSNPVPLYAPNLSPPADSRIHVPASGYCCLECGDAFALEKSLSQHYSRRSVHIEVLCTLCSKTLLFFNKCSLLRHARDHKSKGLVMQCSQLLVKPISADQMFVAAPVNSTAPATPAASSSPKPSPTLDNASSVIPALPLYPDPVRLIRYGTKCPECHKQMRDYMVLATHFQRTTEETEGLTCQVCQMLLPNQCSFCAHQRIHAHKSPYCCPECGVLCRSAYFQTHVKENCLHYARKVGYRCIHCGVIHLTLALLKSHIQERHCQVFHKCAFCPMAFKTASSTMDHSTTQHPTQPHKPSQLIYKCSCEMVFNKKRHIQQHFYQNVSKTQAGVFKCPECPLLFLQKPELMQHVKNTHGVPRNVEELSSLQSSTDTSSNRPGSRAPAEPPATNVAARGSSLTAGRWGRPEAHRRAEARPRMRSTGWTCQECQEWVPDRESYVSHMKKSHGRTLKRYPCRQCEQSFHNPSSLRKHIRNNHDTVKKVYTCGYCTEDSPSFPRPSLLESHISLMHGIRNPDLSQTSKVRHPGGPSPQVNHLKRPVSRMADAPGTSNGATVSSTKRHKSLFQCAKCTFATDSELEFQSHIPQHQVDSSTAQCLLCGLCYTSTSSLNRHLFIVHKVRDQEEGGEDIVEVKVEAPDSEACSGEEVAMETKENGLEECASEPLVTDLGGQQGLALDEDSAQDPQNQPQASQDQNSHALSPQV"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "P10076", 
      "entryName": "ZFP26_MOUSE", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription activator activity, RNA polymerase II-specific [GO:0001228]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 26 (Zfp-26) (Protein mKR3)", 
      "sequence": "METQQVDAVTFEDVAVDFTQEEWTSLDPVQRNLYRDVMLENYQNLATVGGQMFKPSLISWLEKKVELTVIEQGILQEWEMHLKTKRTALQQDRFWSDMSNGMQLGREHSGGEPGDPVQVGAVFSEDSCPQTHSSTSNTGNTFACNLDGKDFQPLLKETSTEENIVQLNQCVKPLIFTPDVSQKKCTPEKSVECSDCGETFVNQLELQTHSSSHREKNIHKSEECGQASTHPISHGGHVIPTEKKYYECKKCEKFFTHPVYLNIHMQSHTVEKPYDCKECGKAFTERSSLIVHLRQHTREKSYECKECGKTFIQPSRLTEHMRSHTGEKPYQCDQCGNAFASSSYLTTHLRTHTGEKPFECNICGKAFTRSSYLLGHIRTHTGEKPYECKVCGKAFSGRSWLTIHLRKHTGERPYPCTECEKAFTSFAQLTEHIKTHTGEKPFRCKVCARTFRNSSCLKTHFRIHTGIKPYKCNYCGKAFTARSGLTKHVLIHNGEKPYECKECGKAFSTSSGLVEHIRIHTGEKPFECYQCGKALAHSSSLVGHLRTHTGEKPFECNQCDKTFTRSSYLRIHMRTHTGEKPYECKECGKTFPERSCLTKHIRTHTGERPYECKECGKGFISFAQLTVHIKTHSSERPFQCKVCTKSFRNSSSLETHFRIHTGVKPYKCSYCGKAFTARSGLTIHLRNHTGEKSYACQECGKAFSTSSGLIAHIRSHKGEKPFECDHCGKAFASSSYLNVHLKIHTGEKPFQCTVCGKTFTCSSYLPVHMRTHTGEKPFQCIICGKSFLWSSYLRVHMRIHTGEKPYVCQYCGKAFTEHSGLNKHLRKHTGEKPYEYKECGENFTTSADANEHETPHWGENL"
    }, 
    {
      "crossReferenceInterPro": "IPR000210;IPR011333;IPR036236;IPR013087;", 
      "entry": "Q92010", 
      "entryName": "ZBT14_CHICK", 
      "geneOntology": "nucleoplasm [GO:0005654]; nucleus [GO:0005634]; DNA-binding transcription factor activity [GO:0003700]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; sequence-specific DNA binding [GO:0043565]; transcription cis-regulatory region binding [GO:0000976]; negative regulation of transcription, DNA-templated [GO:0045892]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger and BTB domain-containing protein 14 (Zinc finger protein 161 homolog) (Zfp-161) (Zinc finger protein 5) (ZF5)", 
      "sequence": "MEFFISMSETIKYNDDDHKTVFLKTLNEQRLEGEFCDIAIVVEDVKFRAHRCVLAACSTYFKKLFKKLEVDSSSVIEIDFLRSDIFEEVLNYMYTAKISVKKEDVNLMMSSGQILGIRFLDKLCSQKRDVSSPEENTQSKSKYCLKINRPIGEPNDTQDDEVEEIGDHDDSPSDVTVEGTPPSQEDGKSPTTTLRVQEAILKELGSEEVRKVNCYGQEVESMETTESKDLGSQTPQALTFNDGISEVKDEQTPGWTTAAGDMKFEYLLYGHREHIVCQACGKTFSDEARLRKHEKLHTADRPFVCEMCTKGFTTQAHLKEHLKIHTGYKPYSCEVCGKSFIRAPDLKKHERVHSNERPFACHMCDKAFKHKSHLKDHERRHRGEKPFVCGSCTKAFAKASDLKRHENNMHSERKQVTTANSIQSETEQLQAAAMAREAEQQLETIACS"
    }, 
    {
      "crossReferenceInterPro": "IPR000210;IPR041588;IPR011333;IPR036236;IPR013087;", 
      "entry": "G5E8B9", 
      "entryName": "ZBT11_MOUSE", 
      "geneOntology": "nucleolus [GO:0005730]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription, DNA-templated [GO:0006355]", 
      "jaccard": 0.8571428571428571, 
      "proteinNames": "Zinc finger and BTB domain-containing protein 11", 
      "sequence": "MSSEESYRAILRYLTNEREPYAPGTEGNVKRKIRKAAACYVVRGGTLYYQRRQRHRKTFAELEVVLQPERRQGLIEAAHLGPGGTHHTRHQTWHDLSKTYWWRGILKQVKDYIKQCSKCQEKLDRSRPISDASEMLEELGLDLDSGEESNESEDDLSNFTSPPSTASKSSKKKPVSKHELVFVDTKGVVKRSSPKHCQAVLKQLNEQRLSNQFCDVTLLIEGEEYKAHKSVLSANSEYFRDLFIEKGAVSSHEAVVDLSGFCKASFLPLLEFAYTSVLSFDFCSMADVAVLARHLFMSEVLEICESVHKLMEEKQLTVYKKGEVQTVASTQDLAAHNGTTTPPGTRNEATTTLSGELGHCEIVLLVNGELPEAEQNGEPEQQPAPQASPEAEASVSPVEGIPEPHPEMGTASLAKESNQPESAVTREDGIVASVHPKISKENVTNASQEDSDTGNDTSPEDIGAKDCPDHSQSPGQPSKDEDTLTEATEKTDSGPDDDTYRSRLRQRSVNEGGYIRLHKGMEKKLQKRKAISKSAVQQVAQKLVQRGKKMKQPKRDAKESTEETAHKCGECGMVFPRRYAFIMHTLKHERARDYKCPLCKKQFQYSASLRAHLIRHTRKEAPTSSSSNSTSTEASGGSSEKGRTKREFICSICGRTLPKLYSLRIHMLKHTGVKPHACQVCGKTFIYKHGLKLHQSLHQSQKQFQCELCVKSFVTKRSLQEHMSIHTGESKYFCSICGKSFHRGSGLSKHLKKHQPKPEVRGYHCTQCEKSFFEARDLRQHMNKHLGVKPFQCQFCDKCYSWKKDWYSHVKSHSVTEPYRCNICGKEFYEKALFRRHVKKATHGKKGRAKQNLERVCDQCGRKFTQLREYRRHMNNHEGVKPFECLTCGVAWADARSLKRHVRTHTGERPYVCPVCSEAYIDARTLRKHMTKFHRDYVPCKIMLEKDTLQFHNQGTQVEHAVSILTADMQEQESSGPQELETVVVTGETMEVLEAVAATEECPSVSTLSDQSIMQVVNYVLAQQQGQKLSEVAEAIQTVEVEVAHMPEAE"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q86XN6", 
      "entryName": "ZN761_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 761", 
      "sequence": "MAFSQGLLTFRDVAIEFSQEEWKCLDPAQRTLYRDVMLENYRNLVSLDISSKCTMKEFLSTAQGNREVFHAGTLQIHESHHNGDFCYQDVDKDIHDYEFQWQEDERNGHEAPMTKIKKLTGITERYDQSHARNKPIKDQLGSSFHSHLPEMHIFQTEEKIDNQVVKSVHDASLVSTAQRISCRPKTHISNNHGNNFWNSSLLTQKQEVHMREKSFQCNESGKAFNYSSLLRKHQIIHLADKYKCDVCGKLFNQKRNLACHRRCHTGENPYKCNECGKTFSQTSSLTCHRRLHTGEKPYKCEECDKAFHFKSILERHRIIHTEEKPYKCNECGKTFRQKSILTRHHRLHTGEKPYKCNECGKTFSHKSSLTCHHRLHTGEKPYKCNECGKTFSHKSSLTCHRRLHTGEKPYKCEECDKAYSFRSNFEIHRKIHTEDNAYKCNECGKTFSRTSSLTCHRRRHTGEQPYKCEECDKAFRFKSNLERHRRIHTGEKPYKCNECGKTFSRKSYLTCHHRLHTGEKAYKCNECGKTFSWKSSLTCHRRLHSGEKPYKCKECGKTFNQQLTLKRHRRLHSGENPYKCEDSDKAYSFKSNLEIHQKIHTEENPYKCNECGKTFSRTSSLTCHRRLHTGEKPYKCEECDKAFRVKSNLEGHRRIHTGEKPYKCNECGKTFSRKSYFICHHRLHTGEKPYKCNECGKNFSQKSSLICHHRLHTGEKPYKCNECGKTFSQKSNLTCHRRLHTGEKQV"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q9GZX5", 
      "entryName": "ZN350_HUMAN", 
      "geneOntology": "nuclear body [GO:0016604]; nuclear matrix [GO:0016363]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; transcription repressor complex [GO:0017053]; DNA binding [GO:0003677]; DNA-binding transcription factor activity [GO:0003700]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; RNA polymerase II intronic transcription regulatory region sequence-specific DNA binding [GO:0001162]; negative regulation of transcription by RNA polymerase II [GO:0000122]; negative regulation of transcription, DNA-templated [GO:0045892]; regulation of transcription by RNA polymerase II [GO:0006357]; regulation of transcription, DNA-templated [GO:0006355]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 350 (KRAB zinc finger protein ZFQR) (Zinc finger and BRCA1-interacting protein with a KRAB domain 1) (Zinc finger protein ZBRK1)", 
      "sequence": "MIQAQESITLEDVAVDFTWEEWQLLGAAQKDLYRDVMLENYSNLVAVGYQASKPDALFKLEQGEQLWTIEDGIHSGACSDIWKVDHVLERLQSESLVNRRKPCHEHDAFENIVHCSKSQFLLGQNHDIFDLRGKSLKSNLTLVNQSKGYEIKNSVEFTGNGDSFLHANHERLHTAIKFPASQKLISTKSQFISPKHQKTRKLEKHHVCSECGKAFIKKSWLTDHQVMHTGEKPHRCSLCEKAFSRKFMLTEHQRTHTGEKPYECPECGKAFLKKSRLNIHQKTHTGEKPYICSECGKGFIQKGNLIVHQRIHTGEKPYICNECGKGFIQKTCLIAHQRFHTGKTPFVCSECGKSCSQKSGLIKHQRIHTGEKPFECSECGKAFSTKQKLIVHQRTHTGERPYGCNECGKAFAYMSCLVKHKRIHTREKQEAAKVENPPAERHSSLHTSDVMQEKNSANGATTQVPSVAPQTSLNISGLLANRNVVLVGQPVVRCAASGDNRGFAQDRNLVNAVNVVVPSVINYVLFYVTENP"
    }, 
    {
      "crossReferenceInterPro": "IPR036236;IPR013087;", 
      "entry": "Q6ZN19", 
      "entryName": "ZN841_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription activator activity, RNA polymerase II-specific [GO:0001228]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger protein 841", 
      "sequence": "MLEGHESYDTENFYFREIRKNLQEVDFQWKDGEINYKEGPMTHKNNLTGQRVRHSQGDVENKHMENQLILRFQSGLGELQKFQTAEKIYGCNQIERTVNNCFLASPLQRIFPGVQTNISRKYGNDFLQLSLPTQDEKTHIREKPYIGNECGKAFRVSSSLINHQMIHTTEKPYRCNESGKAFHRGSLLTVHQIVHTRGKPYQCDVCGRIFRQNSDLVNHRRSHTGDKPYICNECGKSFSKSSHLAVHQRIHTGEKPYKCNRCGKCFSQSSSLATHQTVHTGDKPYKCNECGKTFKRNSSLTAHHIIHAGKKPYTCDVCGKVFYQNSQLVRHQIIHTGETPYKCNECGKVFFQRSRLAGHRRIHTGEKPYKCNECGKVFSQHSHLAVHQRVHTGEKPYKCNECGKAFNWGSLLTVHQRIHTGEKPYKCNVCGKVFNYGGYLSVHMRCHTGEKPLHCNKCGMVFTYYSCLARHQRMHTGEKPYKCNVCGKVFIDSGNLSIHRRSHTGEKPFQCNECGKVFSYYSCLARHRKIHTGEKPYKCNDCGKAYTQRSSLTKHLVIHTGENPYHCNEFGEAFIQSSKLARYHRNPTGEKPHKCSECGRTFSHKTSLVYHQRRHTGEMPYKCIECGKVFNSTTTLARHRRIHTGEKPYKCNECGKVFRYRSGLARHWSIHTGEKPYKCNECGKAFRVRSILLNHQMMHTGEKPYKCNECGKAFIERSNLVYHQRNHTGEKPYKCMECGKAFGRRSCLTKHQRIHSSEKPYKCNECGKSYISRSGLTKHQIKHAGENLTTKLNVERPLDVVLTSGIPK"
    }, 
    {
      "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
      "entry": "Q96NG5", 
      "entryName": "ZN558_HUMAN", 
      "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II transcription regulatory region sequence-specific DNA binding [GO:0000977]; negative regulation of transcription by RNA polymerase II [GO:0000122]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 1.0, 
      "proteinNames": "Zinc finger protein 558", 
      "sequence": "MAAVILPSTAAPSSLFPASQQKGHTQGGELVNELLTSWLRGLVTFEDVAVEFTQEEWALLDPAQRTLYRDVMLENCRNLASLGCRVNKPSLISQLEQDKKVVTEERGILPSTCPDLETLLKAKWLTPKKNVFRKEQSKGVKTERSHRGVKLNECNQCFKVFSTKSNLTQHKRIHTGEKPYDCSQCGKSFSSRSYLTIHKRIHNGEKPYECNHCGKAFSDPSSLRLHLRIHTGEKPYECNQCFHVFRTSCNLKSHKRIHTGENHHECNQCGKAFSTRSSLTGHNSIHTGEKPYECHDCGKTFRKSSYLTQHVRTHTGEKPYECNECGKSFSSSFSLTVHKRIHTGEKPYECSDCGKAFNNLSAVKKHLRTHTGEKPYECNHCGKSFTSNSYLSVHKRIHNRWI"
    }, 
    {
      "crossReferenceInterPro": "IPR000210;IPR011333;IPR036236;IPR013087;", 
      "entry": "Q802Y8", 
      "entryName": "ZB16A_DANRE", 
      "geneOntology": "cytoplasm [GO:0005737]; nucleoplasm [GO:0005654]; nucleus [GO:0005634]; DNA-binding transcription repressor activity, RNA polymerase II-specific [GO:0001227]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; positive regulation of type I interferon production [GO:0032481]; protein ubiquitination [GO:0016567]; regulation of neurogenesis [GO:0050767]; regulation of transcription by RNA polymerase II [GO:0006357]", 
      "jaccard": 0.8461538461538461, 
      "proteinNames": "Zinc finger and BTB domain-containing protein 16-A (Promyelocytic leukemia zinc finger protein-A) (Zinc finger protein PLZF-A)", 
      "sequence": "MDLTKMGMIQLQNPNHPNALLHKANQMRLAGTLCDVVIMVDSQEFHAHRTVLACTSKMFEILFHRNSQHYTLDFLSPKTFQQILEYAYTATLQAKVEDLDDLLYAAEILEIEYLEEQCLKILETIQSSDENDTEVNMNDGGTEDDEERKGRHGRNLVGSKKHSTEESGYVSAAQQALALPGMVDQSPSVSTSFGLSTMSPTKAAVDSLMSIGQSLLQSTMHPGVGAEQPLHGNSHPMMGEIKTEMMQVDESGEHESPKAMESIASSNGERSGEPDKNRDGPGTPTRSSVITSARELHYVRDEGLGDQQAEVSQMGLEAMAGMTEKHLASLYGIPSNHKNEAMLSMPASMASSLHMSPALAMSMDFSAYGGLLPQSFIQREFFSKLGELAAGIKPDGRSLNERCNVCGAELPDNEAIEQHRKLHSGMKTYGCELCGKRFLDSLRLRMHLLSHSAGEKAIVCDQCGAQFQKEDALEAHRQIHTGSDMAIFCLLCGKRFQTQTALQQHMEVHAGVRSYICSECNRTFPSHTALKRHLRSHTAGDHPFECEFCGSCFRDESTLKGHKRIHTGEKPYECNGCGKKFSLKHQLETHYRVHTGEKPFECKLCHQRSRDYSAMIKHLRTHNGASPYQCTICLEYCPSLSAMQKHMKGHKPEDIPPDWRIEKTYLYLCYV"
    }
  ], 
  "reference_protein": {
    "crossReferenceInterPro": "IPR001909;IPR036051;IPR036236;IPR013087;", 
    "entry": "Q08ER8", 
    "entryName": "ZN543_HUMAN", 
    "geneOntology": "nucleus [GO:0005634]; DNA-binding transcription factor activity, RNA polymerase II-specific [GO:0000981]; metal ion binding [GO:0046872]; RNA polymerase II cis-regulatory region sequence-specific DNA binding [GO:0000978]; regulation of transcription by RNA polymerase II [GO:0006357]", 
    "proteinNames": "Zinc finger protein 543", 
    "sequence": "MAASAQVSVTFEDVAVTFTQEEWGQLDAAQRTLYQEVMLETCGLLMSLGCPLFKPELIYQLDHRQELWMATKDLSQSSYPGDNTKPKTTEPTFSHLALPEEVLLQEQLTQGASKNSQLGQSKDQDGPSEMQEVHLKIGIGPQRGKLLEKMSSERDGLGSDDGVCTKITQKQVSTEGDLYECDSHGPVTDALIREEKNSYKCEECGKVFKKNALLVQHERIHTQVKPYECTECGKTFSKSTHLLQHLIIHTGEKPYKCMECGKAFNRRSHLTRHQRIHSGEKPYKCSECGKAFTHRSTFVLHHRSHTGEKPFVCKECGKAFRDRPGFIRHYIIHTGEKPYECIECGKAFNRRSYLTWHQQIHTGVKPFECNECGKAFCESADLIQHYIIHTGEKPYKCMECGKAFNRRSHLKQHQRIHTGEKPYECSECGKAFTHCSTFVLHKRTHTGEKPYECKECGKAFSDRADLIRHFSIHTGEKPYECVECGKAFNRSSHLTRHQQIHTGEKPYECIQCGKAFCRSANLIRHSIIHTGEKPYECSECGKAFNRGSSLTHHQRIHTGRNPTIVTDVGRPFMTAQTSVNIQELLLGKEFLNITTEENLW"
  }
};

// graph payload (with minimalist structure)
const data = {
    nodes: [{ id: "Harry", color: 'red', interpro: "IPR5638207" }, { id: "Sally" }, { id: "Alice" }],
    links: [
      { source: "Harry", target: "Sally", weight: "3", renderLabel : true},
      { source: "Harry", target: "Alice", weight: '1' },
      { source: "Sally", target: "Alice", weight: '1' },
    ],
  };
  
//build graphdata from dataFromFlask
const nodes = [];
const links = [];
  //fill nodes
const graphdata = {
    nodes : {},
    links : {}
}


// the graph configuration, just override the ones you need
const myConfig = {
    nodeHighlightBehavior: true,
    node: {
      color: "lightblue",
      size: 120,
      highlightStrokeColor: "blue",
    },
    link: {
      highlightColor: "lightblue",
      labelProperty: "weight",
      renderLabel: true,
    },
};
  
const onClickNode = function(nodeId) {
    window.alert(`Clicked node ${nodeId}`);
};
  
const onClickLink = function(source, target) {
    window.alert(`Clicked link between ${source} and ${target}`);
    
};

const Nodegraph = () => {
    return (
    <Graph
        id="graph-id" // id is mandatory
        data={data}
        config={myConfig}
        onClickNode={onClickNode}
        onClickLink={onClickLink}
    />
    )
}

export default Nodegraph;


